//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Messages
    {
        public int MessageID { get; set; }
        public string ReceivedMessage { get; set; }
        public string SentMessage { get; set; }
        public Nullable<int> ReceiverMemberID { get; set; }
        public Nullable<int> SenderMemberID { get; set; }
        public Nullable<System.DateTime> TransmissionDate { get; set; }
        public Nullable<int> Control { get; set; }
    
        public virtual Members Members { get; set; }
        public virtual Members Members1 { get; set; }
    }
}
