//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales
    {
        public int SaleID { get; set; }
        public Nullable<System.DateTime> SaleDate { get; set; }
        public Nullable<int> SellerID { get; set; }
        public Nullable<int> BuyerID { get; set; }
        public Nullable<int> ProductID { get; set; }
    
        public virtual Members Members { get; set; }
        public virtual Members Members1 { get; set; }
        public virtual Products Products { get; set; }
    }
}
